# Generated by Django 2.2.1 on 2019-05-03 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(max_length=10000, verbose_name='Текст')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='cat_id',
            field=models.ForeignKey(blank=True, default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to='blog.Category', verbose_name='Связанная заметка'),
        ),
    ]
